services:
  jenkins:
    container_name: jenkins-jdk17
    image: jenkins/jenkins:jdk17
    restart: always
    ports:
      - 80:8080
    volumes:
      - ./jenkins-data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - applications-network
networks:
  applications-network:
    external: true
    name: applications-network